INSERT INTO CUSTOMERS (ID, NAME, LOCATION) 
VALUES(10001,  'Rang', 'HydrabAd');
INSERT INTO CUSTOMERS (ID, NAME, LOCATION) 
VALUES(10002,  'PUL', 'DADA');
INSERT INTO CUSTOMERS (ID, NAME, LOCATION) 
VALUES(10003,  'ADAD', 'HFEFEydrabad');